apiVersion: v1
kind: Pod
metadata:
  name: hello-minikube-pod
  labels:
    app: hello-minikube
spec:
  containers:
    - name: hello-minikube-container
      image: ealen/echo-server
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: env-configmap
      env:
        - name: GREETING
          value: "Warm greetings to"
        - name: HONORIFIC
          value: "The Most Honorable"
        - name: NAME
          value: "Kubernetes"
