apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-minikube-deployment
  labels:
    app: hello-minikube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-minikube
  template:
    metadata:
      labels:
        app: hello-minikube
    spec:
      containers:
        - name: hello-minikube-container
          image: ealen/echo-server
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-configmap
          env:
            - name: GREETING
              value: "Warm greetings to"
            - name: HONORIFIC
              value: "The Most Honorable"
            - name: NAME
              value: "Kubernetes"
