apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-minikube-deployment
  labels:
    app: hello-minikube # deployment label
spec:
  replicas: 3 # used to determine the number of pod replicas
  selector:
    matchLabels:
      app: hello-minikube-pods # should match pod labels below
  template:
    metadata:
      labels:
        app: hello-minikube-pods
    spec:
      containers:
        - name: hello-minikube-container
          image: ealen/echo-server # the image that will be used by each pod
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: env-configmap
          env:
            - name: GREETING
              value: "Warm greetings to"
            - name: HONORIFIC
              value: "The Most Honorable"
            - name: NAME
              value: "Kubernetes"
