apiVersion: v1
kind: Pod
metadata:
  name: hello-minikube-pod
  labels:
    app: hello-minikube
spec:
  containers:
    - name: hello-minikube-container
      image: kicbase/echo-server:1.0
      ports:
        - containerPort: 8080
